// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: sniffer/v1/agent.proto

package snifferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One netns capture the agent must run.
type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pod *PodRef `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	// Interfaces inside the target netns; empty means "any".
	Interfaces []string `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	BpfFilter  string   `protobuf:"bytes,3,opt,name=bpf_filter,json=bpfFilter,proto3" json:"bpf_filter,omitempty"`
	TlsMode    TlsMode  `protobuf:"varint,4,opt,name=tls_mode,json=tlsMode,proto3,enum=sniffer.v1.TlsMode" json:"tls_mode,omitempty"`
	Snaplen    uint32   `protobuf:"varint,5,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetPod() *PodRef {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *Target) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *Target) GetBpfFilter() string {
	if x != nil {
		return x.BpfFilter
	}
	return ""
}

func (x *Target) GetTlsMode() TlsMode {
	if x != nil {
		return x.TlsMode
	}
	return TlsMode_TLS_MODE_UNSPECIFIED
}

func (x *Target) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

// The agent's whole world view. Passed at bootstrap (protojson via argument or
// env) and later refreshed over WatchTargets so pods appearing mid-session do
// not require respawning the agent pod.
type AgentAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Node      string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Opaque id the hub mints per agent incarnation. Agents are recreated as
	// targets move between nodes (T2.3), and a replacement agent restarts its
	// sequence counters; scoping sequences to a stream id keeps the hub from
	// reading a fresh counter as a gap, and lets it discard records from a
	// superseded agent whose stream briefly overlaps its replacement.
	StreamId string    `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Targets  []*Target `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *AgentAssignment) Reset() {
	*x = AgentAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAssignment) ProtoMessage() {}

func (x *AgentAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAssignment.ProtoReflect.Descriptor instead.
func (*AgentAssignment) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentAssignment) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AgentAssignment) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AgentAssignment) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type WatchTargetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Node      string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	AgentPod  string `protobuf:"bytes,3,opt,name=agent_pod,json=agentPod,proto3" json:"agent_pod,omitempty"`
}

func (x *WatchTargetsRequest) Reset() {
	*x = WatchTargetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTargetsRequest) ProtoMessage() {}

func (x *WatchTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTargetsRequest.ProtoReflect.Descriptor instead.
func (*WatchTargetsRequest) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *WatchTargetsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchTargetsRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WatchTargetsRequest) GetAgentPod() string {
	if x != nil {
		return x.AgentPod
	}
	return ""
}

// Agents ship batches to amortise gRPC overhead; the hub fans individual
// records out to subscribers.
type CaptureBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Node      string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Must echo AgentAssignment.stream_id.
	StreamId string           `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Records  []*CaptureRecord `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	// Records the agent knows it lost (tcpdump/kernel drop counters) since the
	// previous batch.
	Dropped uint64 `protobuf:"varint,5,opt,name=dropped,proto3" json:"dropped,omitempty"`
}

func (x *CaptureBatch) Reset() {
	*x = CaptureBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureBatch) ProtoMessage() {}

func (x *CaptureBatch) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureBatch.ProtoReflect.Descriptor instead.
func (*CaptureBatch) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CaptureBatch) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CaptureBatch) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *CaptureBatch) GetRecords() []*CaptureRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *CaptureBatch) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

// End-of-stream tally only. Backpressure is gRPC flow control, and hub-side
// drops are reported over ReportStatus/SessionStats while the capture runs:
// nothing here reaches a still-streaming agent.
type StreamCaptureSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordsAccepted uint64 `protobuf:"varint,1,opt,name=records_accepted,json=recordsAccepted,proto3" json:"records_accepted,omitempty"`
}

func (x *StreamCaptureSummary) Reset() {
	*x = StreamCaptureSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamCaptureSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCaptureSummary) ProtoMessage() {}

func (x *StreamCaptureSummary) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCaptureSummary.ProtoReflect.Descriptor instead.
func (*StreamCaptureSummary) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StreamCaptureSummary) GetRecordsAccepted() uint64 {
	if x != nil {
		return x.RecordsAccepted
	}
	return 0
}

type ReportStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Node      string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	StreamId  string `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*ReportStatusRequest_AgentState
	//	*ReportStatusRequest_TlsState
	//	*ReportStatusRequest_Stats
	//	*ReportStatusRequest_Error
	Payload isReportStatusRequest_Payload `protobuf_oneof:"payload"`
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ReportStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportStatusRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ReportStatusRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (m *ReportStatusRequest) GetPayload() isReportStatusRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ReportStatusRequest) GetAgentState() *AgentStateChanged {
	if x, ok := x.GetPayload().(*ReportStatusRequest_AgentState); ok {
		return x.AgentState
	}
	return nil
}

func (x *ReportStatusRequest) GetTlsState() *TlsStateChanged {
	if x, ok := x.GetPayload().(*ReportStatusRequest_TlsState); ok {
		return x.TlsState
	}
	return nil
}

func (x *ReportStatusRequest) GetStats() *SessionStats {
	if x, ok := x.GetPayload().(*ReportStatusRequest_Stats); ok {
		return x.Stats
	}
	return nil
}

func (x *ReportStatusRequest) GetError() *CaptureError {
	if x, ok := x.GetPayload().(*ReportStatusRequest_Error); ok {
		return x.Error
	}
	return nil
}

type isReportStatusRequest_Payload interface {
	isReportStatusRequest_Payload()
}

type ReportStatusRequest_AgentState struct {
	AgentState *AgentStateChanged `protobuf:"bytes,10,opt,name=agent_state,json=agentState,proto3,oneof"`
}

type ReportStatusRequest_TlsState struct {
	TlsState *TlsStateChanged `protobuf:"bytes,11,opt,name=tls_state,json=tlsState,proto3,oneof"`
}

type ReportStatusRequest_Stats struct {
	Stats *SessionStats `protobuf:"bytes,12,opt,name=stats,proto3,oneof"`
}

type ReportStatusRequest_Error struct {
	Error *CaptureError `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

func (*ReportStatusRequest_AgentState) isReportStatusRequest_Payload() {}

func (*ReportStatusRequest_TlsState) isReportStatusRequest_Payload() {}

func (*ReportStatusRequest_Stats) isReportStatusRequest_Payload() {}

func (*ReportStatusRequest_Error) isReportStatusRequest_Payload() {}

type ReportStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_agent_proto_rawDescGZIP(), []int{6}
}

var File_sniffer_v1_agent_proto protoreflect.FileDescriptor

var file_sniffer_v1_agent_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x6e,
	0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18,
	0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x64, 0x52, 0x65, 0x66, 0x52, 0x03, 0x70, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x70, 0x66,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x70, 0x66, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x08, 0x74, 0x6c, 0x73, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x6e, 0x69,
	0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6c, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x74, 0x6c, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6e, 0x61, 0x70,
	0x6c, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6e, 0x61, 0x70, 0x6c,
	0x65, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x73, 0x22, 0x65, 0x0a, 0x13, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x64, 0x22, 0xad, 0x01, 0x0a, 0x0c,
	0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x22, 0x41, 0x0a, 0x14, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x61,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x22, 0xd2,
	0x02, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x6e,
	0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x6c, 0x73, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6e,
	0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6c, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x74, 0x6c, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x02, 0x0a, 0x12,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x12, 0x1f, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x30, 0x01, 0x12, 0x4d, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x20, 0x2e,
	0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x28,
	0x01, 0x12, 0x51, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1f, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x68, 0x75, 0x63, 0x6b, 0x2f, 0x6b, 0x38, 0x73, 0x2d, 0x73, 0x6e,
	0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sniffer_v1_agent_proto_rawDescOnce sync.Once
	file_sniffer_v1_agent_proto_rawDescData = file_sniffer_v1_agent_proto_rawDesc
)

func file_sniffer_v1_agent_proto_rawDescGZIP() []byte {
	file_sniffer_v1_agent_proto_rawDescOnce.Do(func() {
		file_sniffer_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_sniffer_v1_agent_proto_rawDescData)
	})
	return file_sniffer_v1_agent_proto_rawDescData
}

var file_sniffer_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sniffer_v1_agent_proto_goTypes = []any{
	(*Target)(nil),               // 0: sniffer.v1.Target
	(*AgentAssignment)(nil),      // 1: sniffer.v1.AgentAssignment
	(*WatchTargetsRequest)(nil),  // 2: sniffer.v1.WatchTargetsRequest
	(*CaptureBatch)(nil),         // 3: sniffer.v1.CaptureBatch
	(*StreamCaptureSummary)(nil), // 4: sniffer.v1.StreamCaptureSummary
	(*ReportStatusRequest)(nil),  // 5: sniffer.v1.ReportStatusRequest
	(*ReportStatusResponse)(nil), // 6: sniffer.v1.ReportStatusResponse
	(*PodRef)(nil),               // 7: sniffer.v1.PodRef
	(TlsMode)(0),                 // 8: sniffer.v1.TlsMode
	(*CaptureRecord)(nil),        // 9: sniffer.v1.CaptureRecord
	(*AgentStateChanged)(nil),    // 10: sniffer.v1.AgentStateChanged
	(*TlsStateChanged)(nil),      // 11: sniffer.v1.TlsStateChanged
	(*SessionStats)(nil),         // 12: sniffer.v1.SessionStats
	(*CaptureError)(nil),         // 13: sniffer.v1.CaptureError
}
var file_sniffer_v1_agent_proto_depIdxs = []int32{
	7,  // 0: sniffer.v1.Target.pod:type_name -> sniffer.v1.PodRef
	8,  // 1: sniffer.v1.Target.tls_mode:type_name -> sniffer.v1.TlsMode
	0,  // 2: sniffer.v1.AgentAssignment.targets:type_name -> sniffer.v1.Target
	9,  // 3: sniffer.v1.CaptureBatch.records:type_name -> sniffer.v1.CaptureRecord
	10, // 4: sniffer.v1.ReportStatusRequest.agent_state:type_name -> sniffer.v1.AgentStateChanged
	11, // 5: sniffer.v1.ReportStatusRequest.tls_state:type_name -> sniffer.v1.TlsStateChanged
	12, // 6: sniffer.v1.ReportStatusRequest.stats:type_name -> sniffer.v1.SessionStats
	13, // 7: sniffer.v1.ReportStatusRequest.error:type_name -> sniffer.v1.CaptureError
	2,  // 8: sniffer.v1.AgentIngestService.WatchTargets:input_type -> sniffer.v1.WatchTargetsRequest
	3,  // 9: sniffer.v1.AgentIngestService.StreamCapture:input_type -> sniffer.v1.CaptureBatch
	5,  // 10: sniffer.v1.AgentIngestService.ReportStatus:input_type -> sniffer.v1.ReportStatusRequest
	1,  // 11: sniffer.v1.AgentIngestService.WatchTargets:output_type -> sniffer.v1.AgentAssignment
	4,  // 12: sniffer.v1.AgentIngestService.StreamCapture:output_type -> sniffer.v1.StreamCaptureSummary
	6,  // 13: sniffer.v1.AgentIngestService.ReportStatus:output_type -> sniffer.v1.ReportStatusResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sniffer_v1_agent_proto_init() }
func file_sniffer_v1_agent_proto_init() {
	if File_sniffer_v1_agent_proto != nil {
		return
	}
	file_sniffer_v1_event_proto_init()
	file_sniffer_v1_packet_proto_init()
	file_sniffer_v1_record_proto_init()
	file_sniffer_v1_session_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sniffer_v1_agent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_agent_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AgentAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_agent_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WatchTargetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_agent_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CaptureBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_agent_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StreamCaptureSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_agent_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ReportStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_agent_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReportStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sniffer_v1_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*ReportStatusRequest_AgentState)(nil),
		(*ReportStatusRequest_TlsState)(nil),
		(*ReportStatusRequest_Stats)(nil),
		(*ReportStatusRequest_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sniffer_v1_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sniffer_v1_agent_proto_goTypes,
		DependencyIndexes: file_sniffer_v1_agent_proto_depIdxs,
		MessageInfos:      file_sniffer_v1_agent_proto_msgTypes,
	}.Build()
	File_sniffer_v1_agent_proto = out.File
	file_sniffer_v1_agent_proto_rawDesc = nil
	file_sniffer_v1_agent_proto_goTypes = nil
	file_sniffer_v1_agent_proto_depIdxs = nil
}
