// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: sniffer/v1/agent.proto

package snifferv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentIngestService_WatchTargets_FullMethodName  = "/sniffer.v1.AgentIngestService/WatchTargets"
	AgentIngestService_StreamCapture_FullMethodName = "/sniffer.v1.AgentIngestService/StreamCapture"
	AgentIngestService_ReportStatus_FullMethodName  = "/sniffer.v1.AgentIngestService/ReportStatus"
)

// AgentIngestServiceClient is the client API for AgentIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent-facing API, served by the hub. Kept separate from HubService so agent
// credentials and client credentials can diverge (Phase 4 authn).
type AgentIngestServiceClient interface {
	WatchTargets(ctx context.Context, in *WatchTargetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentAssignment], error)
	StreamCapture(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CaptureBatch, StreamCaptureSummary], error)
	ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error)
}

type agentIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentIngestServiceClient(cc grpc.ClientConnInterface) AgentIngestServiceClient {
	return &agentIngestServiceClient{cc}
}

func (c *agentIngestServiceClient) WatchTargets(ctx context.Context, in *WatchTargetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngestService_ServiceDesc.Streams[0], AgentIngestService_WatchTargets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTargetsRequest, AgentAssignment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngestService_WatchTargetsClient = grpc.ServerStreamingClient[AgentAssignment]

func (c *agentIngestServiceClient) StreamCapture(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CaptureBatch, StreamCaptureSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngestService_ServiceDesc.Streams[1], AgentIngestService_StreamCapture_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CaptureBatch, StreamCaptureSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngestService_StreamCaptureClient = grpc.ClientStreamingClient[CaptureBatch, StreamCaptureSummary]

func (c *agentIngestServiceClient) ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, AgentIngestService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentIngestServiceServer is the server API for AgentIngestService service.
// All implementations must embed UnimplementedAgentIngestServiceServer
// for forward compatibility.
//
// Agent-facing API, served by the hub. Kept separate from HubService so agent
// credentials and client credentials can diverge (Phase 4 authn).
type AgentIngestServiceServer interface {
	WatchTargets(*WatchTargetsRequest, grpc.ServerStreamingServer[AgentAssignment]) error
	StreamCapture(grpc.ClientStreamingServer[CaptureBatch, StreamCaptureSummary]) error
	ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error)
	mustEmbedUnimplementedAgentIngestServiceServer()
}

// UnimplementedAgentIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentIngestServiceServer struct{}

func (UnimplementedAgentIngestServiceServer) WatchTargets(*WatchTargetsRequest, grpc.ServerStreamingServer[AgentAssignment]) error {
	return status.Errorf(codes.Unimplemented, "method WatchTargets not implemented")
}
func (UnimplementedAgentIngestServiceServer) StreamCapture(grpc.ClientStreamingServer[CaptureBatch, StreamCaptureSummary]) error {
	return status.Errorf(codes.Unimplemented, "method StreamCapture not implemented")
}
func (UnimplementedAgentIngestServiceServer) ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedAgentIngestServiceServer) mustEmbedUnimplementedAgentIngestServiceServer() {}
func (UnimplementedAgentIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentIngestServiceServer will
// result in compilation errors.
type UnsafeAgentIngestServiceServer interface {
	mustEmbedUnimplementedAgentIngestServiceServer()
}

func RegisterAgentIngestServiceServer(s grpc.ServiceRegistrar, srv AgentIngestServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentIngestService_ServiceDesc, srv)
}

func _AgentIngestService_WatchTargets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTargetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentIngestServiceServer).WatchTargets(m, &grpc.GenericServerStream[WatchTargetsRequest, AgentAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngestService_WatchTargetsServer = grpc.ServerStreamingServer[AgentAssignment]

func _AgentIngestService_StreamCapture_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentIngestServiceServer).StreamCapture(&grpc.GenericServerStream[CaptureBatch, StreamCaptureSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngestService_StreamCaptureServer = grpc.ClientStreamingServer[CaptureBatch, StreamCaptureSummary]

func _AgentIngestService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentIngestServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentIngestService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentIngestServiceServer).ReportStatus(ctx, req.(*ReportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentIngestService_ServiceDesc is the grpc.ServiceDesc for AgentIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sniffer.v1.AgentIngestService",
	HandlerType: (*AgentIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _AgentIngestService_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTargets",
			Handler:       _AgentIngestService_WatchTargets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCapture",
			Handler:       _AgentIngestService_StreamCapture_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sniffer/v1/agent.proto",
}
