// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: sniffer/v1/packet.proto

package snifferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Where a payload came from. TLS_PLAINTEXT is reserved for Phase 3 and is
// never emitted by Phase 1 agents.
type PacketSource int32

const (
	PacketSource_PACKET_SOURCE_UNSPECIFIED   PacketSource = 0
	PacketSource_PACKET_SOURCE_WIRE          PacketSource = 1
	PacketSource_PACKET_SOURCE_TLS_PLAINTEXT PacketSource = 2
)

// Enum value maps for PacketSource.
var (
	PacketSource_name = map[int32]string{
		0: "PACKET_SOURCE_UNSPECIFIED",
		1: "PACKET_SOURCE_WIRE",
		2: "PACKET_SOURCE_TLS_PLAINTEXT",
	}
	PacketSource_value = map[string]int32{
		"PACKET_SOURCE_UNSPECIFIED":   0,
		"PACKET_SOURCE_WIRE":          1,
		"PACKET_SOURCE_TLS_PLAINTEXT": 2,
	}
)

func (x PacketSource) Enum() *PacketSource {
	p := new(PacketSource)
	*p = x
	return p
}

func (x PacketSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketSource) Descriptor() protoreflect.EnumDescriptor {
	return file_sniffer_v1_packet_proto_enumTypes[0].Descriptor()
}

func (PacketSource) Type() protoreflect.EnumType {
	return &file_sniffer_v1_packet_proto_enumTypes[0]
}

func (x PacketSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketSource.Descriptor instead.
func (PacketSource) EnumDescriptor() ([]byte, []int) {
	return file_sniffer_v1_packet_proto_rawDescGZIP(), []int{0}
}

// Values match libpcap DLT_* / pcap linktype numbers so sinks can pass them
// straight into a pcap/pcapng writer.
type LinkType int32

const (
	LinkType_LINK_TYPE_UNSPECIFIED LinkType = 0
	LinkType_LINK_TYPE_ETHERNET    LinkType = 1
	LinkType_LINK_TYPE_RAW         LinkType = 101
	LinkType_LINK_TYPE_LINUX_SLL   LinkType = 113
	LinkType_LINK_TYPE_LINUX_SLL2  LinkType = 276
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0:   "LINK_TYPE_UNSPECIFIED",
		1:   "LINK_TYPE_ETHERNET",
		101: "LINK_TYPE_RAW",
		113: "LINK_TYPE_LINUX_SLL",
		276: "LINK_TYPE_LINUX_SLL2",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_UNSPECIFIED": 0,
		"LINK_TYPE_ETHERNET":    1,
		"LINK_TYPE_RAW":         101,
		"LINK_TYPE_LINUX_SLL":   113,
		"LINK_TYPE_LINUX_SLL2":  276,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_sniffer_v1_packet_proto_enumTypes[1].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_sniffer_v1_packet_proto_enumTypes[1]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_sniffer_v1_packet_proto_rawDescGZIP(), []int{1}
}

// PodRef identifies a capture target across the whole system. Every packet and
// event carries one so the client can tag PCAPng output without extra lookups.
type PodRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid       string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Node      string `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	// Container runtime id (e.g. "containerd://<sha>") whose netns is captured.
	ContainerId string `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (x *PodRef) Reset() {
	*x = PodRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRef) ProtoMessage() {}

func (x *PodRef) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRef.ProtoReflect.Descriptor instead.
func (*PodRef) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_packet_proto_rawDescGZIP(), []int{0}
}

func (x *PodRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodRef) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PodRef) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PodRef) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type PacketFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pod       *PodRef                `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Source    PacketSource           `protobuf:"varint,2,opt,name=source,proto3,enum=sniffer.v1.PacketSource" json:"source,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LinkType  LinkType               `protobuf:"varint,4,opt,name=link_type,json=linkType,proto3,enum=sniffer.v1.LinkType" json:"link_type,omitempty"`
	// Length on the wire before snaplen truncation; equals len(payload) when the
	// packet was captured whole.
	OriginalLength uint32 `protobuf:"varint,5,opt,name=original_length,json=originalLength,proto3" json:"original_length,omitempty"`
	Payload        []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Per-agent monotonic counter, lets the hub detect gaps without timestamps.
	Sequence uint64 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *PacketFrame) Reset() {
	*x = PacketFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFrame) ProtoMessage() {}

func (x *PacketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFrame.ProtoReflect.Descriptor instead.
func (*PacketFrame) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_packet_proto_rawDescGZIP(), []int{1}
}

func (x *PacketFrame) GetPod() *PodRef {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *PacketFrame) GetSource() PacketSource {
	if x != nil {
		return x.Source
	}
	return PacketSource_PACKET_SOURCE_UNSPECIFIED
}

func (x *PacketFrame) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PacketFrame) GetLinkType() LinkType {
	if x != nil {
		return x.LinkType
	}
	return LinkType_LINK_TYPE_UNSPECIFIED
}

func (x *PacketFrame) GetOriginalLength() uint32 {
	if x != nil {
		return x.OriginalLength
	}
	return 0
}

func (x *PacketFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PacketFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Agents ship batches to amortise gRPC overhead; the hub fans individual
// frames out to subscribers.
type PacketBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string         `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Node      string         `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Frames    []*PacketFrame `protobuf:"bytes,3,rep,name=frames,proto3" json:"frames,omitempty"`
	// Packets the agent knows it lost (tcpdump/kernel drop counters) since the
	// previous batch.
	Dropped uint64 `protobuf:"varint,4,opt,name=dropped,proto3" json:"dropped,omitempty"`
}

func (x *PacketBatch) Reset() {
	*x = PacketBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sniffer_v1_packet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketBatch) ProtoMessage() {}

func (x *PacketBatch) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_packet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketBatch.ProtoReflect.Descriptor instead.
func (*PacketBatch) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_packet_proto_rawDescGZIP(), []int{2}
}

func (x *PacketBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketBatch) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PacketBatch) GetFrames() []*PacketFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *PacketBatch) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

var File_sniffer_v1_packet_proto protoreflect.FileDescriptor

var file_sniffer_v1_packet_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x6e, 0x69, 0x66, 0x66,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x06, 0x50, 0x6f, 0x64, 0x52, 0x65,
	0x66, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb1, 0x02, 0x0a,
	0x0b, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x03,
	0x70, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x6e, 0x69, 0x66,
	0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x66, 0x52, 0x03, 0x70,
	0x6f, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x31,
	0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x8b, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x2a, 0x66,
	0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d,
	0x0a, 0x19, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x57,
	0x49, 0x52, 0x45, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f,
	0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54, 0x4c, 0x53, 0x5f, 0x50, 0x4c, 0x41, 0x49, 0x4e,
	0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x2a, 0x84, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16,
	0x0a, 0x12, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x54, 0x48, 0x45,
	0x52, 0x4e, 0x45, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x57, 0x10, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x49, 0x4e,
	0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x49, 0x4e, 0x55, 0x58, 0x5f, 0x53, 0x4c, 0x4c,
	0x10, 0x71, 0x12, 0x19, 0x0a, 0x14, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4c, 0x49, 0x4e, 0x55, 0x58, 0x5f, 0x53, 0x4c, 0x4c, 0x32, 0x10, 0x94, 0x02, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x68, 0x75,
	0x63, 0x6b, 0x2f, 0x6b, 0x38, 0x73, 0x2d, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x6e,
	0x69, 0x66, 0x66, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sniffer_v1_packet_proto_rawDescOnce sync.Once
	file_sniffer_v1_packet_proto_rawDescData = file_sniffer_v1_packet_proto_rawDesc
)

func file_sniffer_v1_packet_proto_rawDescGZIP() []byte {
	file_sniffer_v1_packet_proto_rawDescOnce.Do(func() {
		file_sniffer_v1_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_sniffer_v1_packet_proto_rawDescData)
	})
	return file_sniffer_v1_packet_proto_rawDescData
}

var file_sniffer_v1_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sniffer_v1_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sniffer_v1_packet_proto_goTypes = []any{
	(PacketSource)(0),             // 0: sniffer.v1.PacketSource
	(LinkType)(0),                 // 1: sniffer.v1.LinkType
	(*PodRef)(nil),                // 2: sniffer.v1.PodRef
	(*PacketFrame)(nil),           // 3: sniffer.v1.PacketFrame
	(*PacketBatch)(nil),           // 4: sniffer.v1.PacketBatch
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_sniffer_v1_packet_proto_depIdxs = []int32{
	2, // 0: sniffer.v1.PacketFrame.pod:type_name -> sniffer.v1.PodRef
	0, // 1: sniffer.v1.PacketFrame.source:type_name -> sniffer.v1.PacketSource
	5, // 2: sniffer.v1.PacketFrame.timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: sniffer.v1.PacketFrame.link_type:type_name -> sniffer.v1.LinkType
	3, // 4: sniffer.v1.PacketBatch.frames:type_name -> sniffer.v1.PacketFrame
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sniffer_v1_packet_proto_init() }
func file_sniffer_v1_packet_proto_init() {
	if File_sniffer_v1_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sniffer_v1_packet_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PodRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_packet_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PacketFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sniffer_v1_packet_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PacketBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sniffer_v1_packet_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sniffer_v1_packet_proto_goTypes,
		DependencyIndexes: file_sniffer_v1_packet_proto_depIdxs,
		EnumInfos:         file_sniffer_v1_packet_proto_enumTypes,
		MessageInfos:      file_sniffer_v1_packet_proto_msgTypes,
	}.Build()
	File_sniffer_v1_packet_proto = out.File
	file_sniffer_v1_packet_proto_rawDesc = nil
	file_sniffer_v1_packet_proto_goTypes = nil
	file_sniffer_v1_packet_proto_depIdxs = nil
}
